aws: fix f-string error when print log
python11 f-string does not accept double quotation, update to single.
Traceback (most recent call last):
  File "/home/ec2/p3_venv/bin/os-tests", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/ec2/p3_venv/lib64/python3.11/site-packages/os_tests/os_tests_run.py", line 38, in main
    vms, disks, nics, nets = init_provider(params=params)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2/p3_venv/lib64/python3.11/site-packages/os_tests/libs/utils_lib.py", line 157, in init_provider
    from .resources_aws import EC2VM,EC2Volume,EC2NIC
  File "/home/ec2/p3_venv/lib64/python3.11/site-packages/os_tests/libs/resources_aws.py", line 98
    LOG.info(f"Use exists {self.id} which is_allow_delete is {self.params.get("is_allow_delete")}")
                                                                               ^^^^^^^^^^^^^^^
SyntaxError: f-string: unmatched '('

Signed-off-by: Frank Liang <xiliang@redhat.com>